name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.token }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sundaeparty/devcontainer:dev
    
    - name: Push dev version to Dockerhub
      if: startsWith(github.ref, 'refs/heads/main/')
      run: docker push sundaeparty/devcontainer:dev
    
    - name: Tag new docker image version
      if: startsWith(github.ref, 'refs/tags/v')
      run: docker tag sundaeparty/devcontainer:dev sundaeparty/devcontainer:${GITHUB_REF#refs/tags/}
    
    - name: Push new taged version to Dockerhub
      if: startsWith(github.ref, 'refs/tags/v')
      run: docker push sundaeparty/devcontainer:${GITHUB_REF#refs/tags/}
    
    - name: Tag new docker image version to latest
      if: startsWith(github.ref, 'refs/tags/v')
      run: docker tag sundaeparty/devcontainer:dev sundaeparty/devcontainer:latest
    
    - name: Push latest version to Dockerhub
      if: startsWith(github.ref, 'refs/tags/v')
      run: docker push sundaeparty/devcontainer:latest
